name: Pull Request
on:
  push:
  pull_request:
    types: [opened reopened syncronize]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v1
      - name: Lint code
        run: npm run eslint
      - name: Check formatting
        run: npm run prettier:check
      - name: Check spelling
        run: npm run cspell
      - name: Check dependencies
        run: npm run depcruise
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: packages/react
          buildScriptName: build:storybook
          exitOnceUploaded: true
